FROM python:3.7.13-alpine3.16

ARG HOST_PORT
ARG HOST_URL

ENV HOST_URL=$HOST_URL
ENV HOST_PORT=$HOST_PORT

WORKDIR /app

COPY . .

RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt

ENTRYPOINT ["python3","main.py"]