version: "3.3"
services:
    flaskServer:
        build:
            context: ../
            dockerfile: ./dockerfiles/dockerfile.flask.yml
            args:
                - HOST_URL=$HOST_URL
                - HOST_PORT=$HOST_PORT
        image: flask-server:latest
        container_name: flask-server
        environment:
            - HOST_URL=0.0.0.0
            - HOST_PORT=8081
        tty: true
        restart: always
        ports:
            - 8081:8081
    nginx:
        build:
            context: ../
            dockerfile: ./dockerfiles/dockerfile.nginx.yml
        image: nginx:latest
        container_name: nginx
        tty: true
        restart: always
        ports:
            - 80:80
    
        
