apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: flask
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nginx
spec: {}
status: {}