apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: flaskserver
  name: flaskserver
spec:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: flaskserver
  type: NodePort
status:
  loadBalancer: {}
