apiVersion: v1
kind: Service
metadata:
  annotations:
   service.beta.kubernetes.io/aws-load-balancer-internal: "true"
   service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
  creationTimestamp: null
  namespace: nginx
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30693
  selector:
    app: nginx
  type: NodePort
status:
  loadBalancer: {}